title: Software Engineering - The Journey
author: Phillip Smith
email: psmith@phillipbsmith.com
description: >-
  My journey to learn to code.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # your site's origin, e.g. 

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
  - jekyll-menus

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
