# Site settings
author: Phillip Smith
title: Software Engineering The Journey 
header-img: img/home-bg.png
email: pbsmith82@gmail.com
copyright_name: Phillip Smith
description: > # this means to ignore newlines until "baseurl:"
  Learning to Code 
baseurl: /_posts # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  pbsmith82

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

theme: jekyll-theme-cayman